### PR TITLE
fix(ci): bump aw-server-rust submodule to fix time-0.3.30/Rust-1.85+ build failure

### PR DESCRIPTION
**Pull request by TimeToBuildBob**
## Problem

The `aw-server-rust` submodule was pinned to dc70318 which uses `time-0.3.30` (via Cargo.lock). That version fails to compile with Rust stable >= 1.85 due to a type inference regression:

```
error[E0282]: type annotations needed for `Box<_>`
  --> .cargo/registry/.../time-0.3.30/src/format_description/parse/mod.rs:83:9
```

This broke the `Build aw-server-rust` CI job on master ~18h ago (run https://github.com/ActivityWatch/aw-android/actions/runs/26303317730).

## Fix

Bump the submodule pointer from dc70318 → 288decb (latest aw-server-rust master).

`aw-server-rust` master already carries the fix — its Cargo.lock pins `time-0.3.47` which compiles cleanly on all current stable Rust toolchains. The bump also includes a few other recent fixes merged into aw-server-rust since the last submodule update.

## Why not pin Rust version instead?

Pinning Rust avoids the root cause (stale submodule) and creates a new maintenance burden. Updating the submodule is the correct fix.

### CODE REVIEW

**Comment by TimeToBuildBob** [comment]
## CI Status Summary

The fix itself passes — **Build aw-server-rust** ✅ completed successfully on this run.

The other failing jobs are expected fork-PR behavior, not regressions from this change:

| Job | Status | Reason |
|-----|--------|--------|
| **Build aw-server-rust** | ✅ PASS | The actual fix — confirms time-0.3.47 compiles cleanly |
| **Get latest versionCode** | ❌ FAIL | "Load Fastlane secrets" step — expected on fork PRs (secrets withheld) |
| **Test** | ❌ FAIL | "Check that jniLibs present" — jniLibs cached in master, unavailable on fork PR cache |
| **Test E2E** | ❌ FAIL | Setup failed — infrastructure/resource issue unrelated to this change |

The same test jobs were also **skipped** on the original master branch because Build aw-server-rust blocked them first. This PR fixes that blocking build failure, and the failing tests here are the same fork-PR restrictions that exist for all external contributors.

This PR is ready for maintainer review/merge.
