### PR TITLE
fix(ci): pin Rust to 1.79.0 to avoid E0282 in time crate on 1.80+

### PR DESCRIPTION
**Pull request by TimeToBuildBob**
## Summary

- `aw-server-rust@dc70318` depends on an older version of the `time` crate that fails to compile on Rust 1.80+ due to tightened type inference (`E0282: type annotations needed for Box<_>`)
- Master CI has been failing on every push since Rust stable moved to 1.80+
- Pin `dtolnay/rust-toolchain` to `1.79.0` in the `Build aw-server-rust` job until aw-server-rust updates its dependencies

## Error (from master CI run 26290684290)

```
error[E0282]: type annotations needed for `Box<_>`
error: could not compile `time` (lib) due to 1 previous error
```

## Fix

Change `dtolnay/rust-toolchain@stable` → `dtolnay/rust-toolchain@1.79.0` with a comment explaining the pin. Unpin once `aw-server-rust` updates its `time` crate dependency.

## Test plan

- [ ] CI Build aw-server-rust job passes with pinned Rust 1.79.0

### CODE REVIEW

**Comment by TimeToBuildBob** [comment]
Note: the 'Get latest versionCode' check fails on fork PRs because it requires Fastlane secrets (Play Store access) that aren't available in fork CI runs. This is expected and unrelated to this change. The key check is 'Build aw-server-rust' — that's the one that was failing due to the Rust/time crate issue.

**Comment by 0xbrayo** [comment]
@TimeToBuildBob is this PR still necessary since you bumped the aw-server-rust version

**Comment by TimeToBuildBob** [comment]
No. This PR is obsolete now.

PR #165 merged on 2026-05-23 and fixed the same Rust/time failure the right way by bumping the `aw-server-rust` submodule from `dc70318` to `288decb`. That newer submodule pins `time 0.3.47`, so the `Build aw-server-rust` job is back to passing on stable Rust.

Verification:
- merged replacement: `ActivityWatch/aw-android#165`
- merged workflow run `26337176502`: `Build aw-server-rust` passed

`master` is still red overall, but for unrelated reasons (`actions/upload-artifact@v3` deprecation in other jobs and a separate cache-miss/test path), not the original `E0282` failure this PR worked around.

Closing this as superseded by #165.
